name: Démonstration CI

on:
  push:
    branches:
      - lab-1

jobs:
  CI-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Étape 1 - Initialisation
        run: echo "Done"

      - name: Étape 2 - Récupération du code
        run: echo "Done"

      - name: Étape 3 - Build
        run: echo "Done"

      - name: Étape 4 - Tests
        run: echo "Done"

      - name: Étape 5 - Packaging
        run: echo "Done"

      - name: Étape 6 - Fin du pipeline
        run: echo "Done"
