name: Démonstration CI

on:
  push:
    branches:
      - lab-1

jobs:
  CI-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Étape 1 - Initialisation
        run: echo "Initialisation terminée"

      - name: Étape 2 - Récupération du code
        run: echo "Code récupéré"

      - name: Étape 3 - Build
        run: echo "Build terminé"

      - name: Étape 4 - Tests
        run: echo "Tests réussis"

      - name: Étape 5 - Packaging
        run: echo "Package prêt"

      - name: Étape 6 - Fin du pipeline
        run: echo "Le Sénégal gagne la coupe d'afrique"
